version: '3'

services:
  web:
    container_name: web 
    image: gd890121/django:v2
    ports:
      - "8000:8000"
  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=django
      - MYSQL_DATABASE=django
      - MYSQL_PASSWORD=1234
    volumes:
      - "/var/lib/docker/volumes/mysql/_data:/var/lib/mysql"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

        
    
            

    
